import 'package:flutter/material.dart';
import 'package:share_plus/share_plus.dart';
import 'package:video_summariser_yt/video_summary/models/SummaryDataModel.dart';
import 'package:youtube_player_flutter/youtube_player_flutter.dart';
import 'package:youtube_player_iframe/youtube_player_iframe.dart' as yt_iframe;

class SavedSummaryListItem extends StatefulWidget {
  const SavedSummaryListItem({
    super.key,
    required this.summaries,
    required this.index,
    required this.onPressed,
  });

  final List<SummaryDataModel> summaries;
  final int index;

  final Function()? onPressed;

  @override
  State<SavedSummaryListItem> createState() => _SavedSummaryListItemState();
}

class _SavedSummaryListItemState extends State<SavedSummaryListItem> {
  final _ytController = yt_iframe.YoutubePlayerController(
    params: const yt_iframe.YoutubePlayerParams(
      mute: true,
      showControls: true,
      showFullscreenButton: true,
    ),
  );

  @override
  void initState() {
    String vId =
        YoutubePlayer.convertUrlToId(widget.summaries[widget.index].videoUrl) ??
            "";
    _ytController.cueVideoById(videoId: vId);
    super.initState();
  }

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: const EdgeInsets.all(8.0),
      child: Card(
        child: Padding(
          padding: const EdgeInsets.all(20.0),
          child: Column(
            children: [
              const SizedBox(height: 20),
              Text(
                widget.summaries[widget.index].selectedModel,
                style: const TextStyle(fontSize: 20),
              ),
              const SizedBox(height: 20),
              yt_iframe.YoutubePlayer(controller: _ytController),
              const SizedBox(height: 20),
              Row(
                mainAxisAlignment: MainAxisAlignment.spaceBetween,
                children: [
                  IconButton(
                    onPressed: widget.onPressed,
                    icon: Icon(
                      Icons.delete,
                      color: Colors.grey.shade500,
                    ),
                  ),
                  IconButton(
                    onPressed: () async {
                      await Share.share(
                          'Summary Generated by YT Video Summarizer app\n\nVideo URL: ${widget.summaries[widget.index].videoUrl}\n\n${widget.summaries[widget.index].summaryText}');
                    },
                    icon: Icon(
                      Icons.share,
                      color: Colors.grey.shade500,
                    ),
                  ),
                ],
              ),
              const SizedBox(height: 20),
              SelectableText(widget.summaries[widget.index].summaryText),
            ],
          ),
        ),
      ),
    );
  }
}
